"""architecture_security_upgrades

Revision ID: e0c35f72c87d
Revises: None
Create Date: 2026-09-05 12:11:21.623061

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0c35f72c87d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_webhook_events',
    sa.Column('meta_message_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_webhook_events_id'), 'meta_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_meta_webhook_events_meta_message_id'), 'meta_webhook_events', ['meta_message_id'], unique=False)
    op.create_index(op.f('ix_meta_webhook_events_status'), 'meta_webhook_events', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_customer_id'), 'applications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('webhook_configs',
    sa.Column('application_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('secret', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscribed_events', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_configs_application_id'), 'webhook_configs', ['application_id'], unique=False)
    op.create_index(op.f('ix_webhook_configs_id'), 'webhook_configs', ['id'], unique=False)
    op.add_column('api_keys', sa.Column('application_id', sa.UUID(as_uuid=False), nullable=True))
    from sqlalchemy.dialects.postgresql import ENUM
    env_enum = ENUM('DEVELOPMENT', 'PRODUCTION', name='environmenttype', create_type=False)
    try:
        env_enum.create(op.get_bind())
    except Exception:
        pass
    op.add_column('api_keys', sa.Column('environment', sa.Enum('DEVELOPMENT', 'PRODUCTION', name='environmenttype'), nullable=True, server_default='DEVELOPMENT'))
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('idx_api_keys_customer'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_status'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_application_id'), 'api_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_api_keys_customer_id'), 'api_keys', ['customer_id'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chk_api_keys_revoked'), 'api_keys', type_='check')
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_customer'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_customer_id'), 'audit_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'metadata')
    op.drop_index(op.f('idx_customer_users_user'), table_name='customer_users')
    op.alter_column('customers', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.add_column('idempotency_keys', sa.Column('application_id', sa.UUID(as_uuid=False), nullable=True))
    op.alter_column('idempotency_keys', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('idempotency_keys_customer_id_idempotency_key_endpoint_key'), 'idempotency_keys', type_='unique')
    op.drop_index(op.f('idx_idempotency_customer'), table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_application_id'), 'idempotency_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_customer_id'), 'idempotency_keys', ['customer_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_id'), 'idempotency_keys', ['id'], unique=False)
    op.create_foreign_key(None, 'idempotency_keys', 'applications', ['application_id'], ['id'])
    op.alter_column('message_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_message_events_message'), table_name='message_events')
    op.drop_index(op.f('idx_message_events_type'), table_name='message_events')
    op.create_index(op.f('ix_message_events_event_type'), 'message_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_message_events_id'), 'message_events', ['id'], unique=False)
    op.create_index(op.f('ix_message_events_message_id'), 'message_events', ['message_id'], unique=False)
    op.drop_index(op.f('idx_messages_created'), table_name='messages')
    op.drop_index(op.f('idx_messages_customer'), table_name='messages')
    op.drop_index(op.f('idx_messages_otp_request'), table_name='messages')
    op.drop_index(op.f('idx_messages_provider_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_status'), table_name='messages')
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_otp_request_id'), 'messages', ['otp_request_id'], unique=False)
    op.create_index(op.f('ix_messages_provider_message_id'), 'messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.drop_index(op.f('idx_meta_accounts_customer'), table_name='meta_accounts')
    op.create_index(op.f('ix_meta_accounts_customer_id'), 'meta_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_meta_accounts_id'), 'meta_accounts', ['id'], unique=False)
    op.add_column('otp_requests', sa.Column('application_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_index(op.f('idx_otp_created'), table_name='otp_requests')
    op.drop_index(op.f('idx_otp_customer'), table_name='otp_requests')
    op.drop_index(op.f('idx_otp_expires'), table_name='otp_requests')
    op.drop_index(op.f('idx_otp_phone'), table_name='otp_requests')
    op.drop_index(op.f('idx_otp_status'), table_name='otp_requests')
    op.drop_constraint(op.f('otp_requests_request_id_key'), 'otp_requests', type_='unique')
    op.create_index(op.f('ix_otp_requests_application_id'), 'otp_requests', ['application_id'], unique=False)
    op.create_index(op.f('ix_otp_requests_created_at'), 'otp_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_requests_customer_id'), 'otp_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_otp_requests_expires_at'), 'otp_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_requests_id'), 'otp_requests', ['id'], unique=False)
    op.create_index(op.f('ix_otp_requests_phone_number'), 'otp_requests', ['phone_number'], unique=False)
    op.create_index(op.f('ix_otp_requests_request_id'), 'otp_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_otp_requests_status'), 'otp_requests', ['status'], unique=False)
    op.create_foreign_key(None, 'otp_requests', 'applications', ['application_id'], ['id'])
    op.drop_constraint(op.f('chk_otp_attempts'), 'otp_requests', type_='check')
    op.alter_column('otp_verifications', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index(op.f('idx_otp_verifications_request'), table_name='otp_verifications')
    op.drop_constraint(op.f('otp_verifications_otp_request_id_attempt_number_key'), 'otp_verifications', type_='unique')
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_otp_request_id'), 'otp_verifications', ['otp_request_id'], unique=False)
    op.alter_column('payment_orders', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_payment_orders_customer'), table_name='payment_orders')
    op.drop_index(op.f('idx_payment_orders_status'), table_name='payment_orders')
    op.create_index(op.f('ix_payment_orders_customer_id'), 'payment_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=False)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payments', 'provider_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_payments_order'), table_name='payments')
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_order_id'), 'payments', ['payment_order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.alter_column('pricing_plans', 'monthly_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.alter_column('pricing_rules', 'price_per_message',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_pricing_rules_channel_country'), table_name='pricing_rules')
    op.drop_index(op.f('idx_pricing_rules_plan'), table_name='pricing_rules')
    op.create_index(op.f('ix_pricing_rules_channel'), 'pricing_rules', ['channel'], unique=False)
    op.create_index(op.f('ix_pricing_rules_country_code'), 'pricing_rules', ['country_code'], unique=False)
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_plan_id'), 'pricing_rules', ['plan_id'], unique=False)
    op.alter_column('rate_limit_records', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index(op.f('idx_rate_limit_customer_action_window'), table_name='rate_limit_records')
    op.drop_index(op.f('idx_rate_limit_phone_action_window'), table_name='rate_limit_records')
    op.create_index(op.f('ix_rate_limit_records_customer_id'), 'rate_limit_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_id'), 'rate_limit_records', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_phone_number'), 'rate_limit_records', ['phone_number'], unique=False)
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'balance_before',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'balance_after',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_wallet_transactions_created'), table_name='wallet_transactions')
    op.drop_index(op.f('idx_wallet_transactions_reference'), table_name='wallet_transactions')
    op.drop_index(op.f('idx_wallet_transactions_wallet'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_reference_id'), 'wallet_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('wallets_customer_id_key'), 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_customer_id'), 'wallets', ['customer_id'], unique=True)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('idx_webhook_external_id'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_received'), table_name='webhook_events')
    op.drop_index(op.f('idx_webhook_status'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_external_event_id'), 'webhook_events', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processing_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.drop_index(op.f('idx_whatsapp_numbers_meta_account'), table_name='whatsapp_numbers')
    op.create_index(op.f('ix_whatsapp_numbers_id'), 'whatsapp_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_meta_account_id'), 'whatsapp_numbers', ['meta_account_id'], unique=False)
    op.drop_index(op.f('idx_whatsapp_templates_number'), table_name='whatsapp_templates')
    op.drop_constraint(op.f('whatsapp_templates_whatsapp_number_id_name_language_code_key'), 'whatsapp_templates', type_='unique')
    op.create_index(op.f('ix_whatsapp_templates_id'), 'whatsapp_templates', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_whatsapp_number_id'), 'whatsapp_templates', ['whatsapp_number_id'], unique=False)
    
    # --- DATA MIGRATION ---
    op.execute("""
        INSERT INTO applications (id, customer_id, name, created_at, updated_at)
        SELECT gen_random_uuid(), id, 'Default App', NOW(), NOW()
        FROM customers;
    """)
    op.execute("""
        UPDATE otp_requests o 
        SET application_id = (SELECT id FROM applications a WHERE a.customer_id = o.customer_id LIMIT 1);
    """)
    op.execute("""
        UPDATE idempotency_keys i 
        SET application_id = (SELECT id FROM applications a WHERE a.customer_id = i.customer_id LIMIT 1);
    """)
    # Removed fallback
    # Wait, api_keys in original schema had customer_id. So:
    op.execute("""
        UPDATE api_keys k 
        SET application_id = (SELECT id FROM applications a WHERE a.customer_id = k.customer_id LIMIT 1);
    """)
    
    # Delete orphaned records if customer_id doesn't exist
    op.execute("DELETE FROM otp_requests WHERE application_id IS NULL;")
    op.execute("DELETE FROM idempotency_keys WHERE application_id IS NULL;")
    op.execute("DELETE FROM api_keys WHERE application_id IS NULL;")
    
    # Set NOT NULL
    op.alter_column('otp_requests', 'application_id', nullable=False)
    op.alter_column('idempotency_keys', 'application_id', nullable=False)
    op.alter_column('api_keys', 'application_id', nullable=False)
    op.alter_column('api_keys', 'environment', nullable=False)
    op.alter_column('api_keys', 'updated_at', nullable=False)
    
    # Fix Webhook Event Unique Constraint duplicates
    op.execute("""
        DELETE FROM webhook_events 
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY external_event_id ORDER BY received_at DESC) as rnum
                FROM webhook_events 
                WHERE external_event_id IS NOT NULL
            ) t WHERE t.rnum > 1
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_templates_whatsapp_number_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_id'), table_name='whatsapp_templates')
    op.create_unique_constraint(op.f('whatsapp_templates_whatsapp_number_id_name_language_code_key'), 'whatsapp_templates', ['whatsapp_number_id', 'name', 'language_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_whatsapp_templates_number'), 'whatsapp_templates', ['whatsapp_number_id'], unique=False)
    op.drop_index(op.f('ix_whatsapp_numbers_meta_account_id'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_id'), table_name='whatsapp_numbers')
    op.create_index(op.f('idx_whatsapp_numbers_meta_account'), 'whatsapp_numbers', ['meta_account_id'], unique=False)
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processing_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_external_event_id'), table_name='webhook_events')
    op.create_index(op.f('idx_webhook_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('idx_webhook_received'), 'webhook_events', ['received_at'], unique=False)
    op.create_index(op.f('idx_webhook_external_id'), 'webhook_events', ['external_event_id'], unique=False)
    op.alter_column('webhook_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_customer_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_customer_id_key'), 'wallets', ['customer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_reference_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.create_index(op.f('idx_wallet_transactions_wallet'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_wallet_transactions_reference'), 'wallet_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index(op.f('idx_wallet_transactions_created'), 'wallet_transactions', ['created_at'], unique=False)
    op.alter_column('wallet_transactions', 'balance_after',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'balance_before',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_rate_limit_records_phone_number'), table_name='rate_limit_records')
    op.drop_index(op.f('ix_rate_limit_records_id'), table_name='rate_limit_records')
    op.drop_index(op.f('ix_rate_limit_records_customer_id'), table_name='rate_limit_records')
    op.create_index(op.f('idx_rate_limit_phone_action_window'), 'rate_limit_records', ['phone_number', 'action', 'window_start'], unique=False)
    op.create_index(op.f('idx_rate_limit_customer_action_window'), 'rate_limit_records', ['customer_id', 'action', 'window_start'], unique=False)
    op.alter_column('rate_limit_records', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_index(op.f('ix_pricing_rules_plan_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_country_code'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_channel'), table_name='pricing_rules')
    op.create_index(op.f('idx_pricing_rules_plan'), 'pricing_rules', ['plan_id'], unique=False)
    op.create_index(op.f('idx_pricing_rules_channel_country'), 'pricing_rules', ['channel', 'country_code'], unique=False)
    op.alter_column('pricing_rules', 'price_per_message',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=False)
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.alter_column('pricing_plans', 'monthly_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('idx_payments_order'), 'payments', ['payment_order_id'], unique=False)
    op.alter_column('payments', 'provider_response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_customer_id'), table_name='payment_orders')
    op.create_index(op.f('idx_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('idx_payment_orders_customer'), 'payment_orders', ['customer_id'], unique=False)
    op.alter_column('payment_orders', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_otp_verifications_otp_request_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.create_unique_constraint(op.f('otp_verifications_otp_request_id_attempt_number_key'), 'otp_verifications', ['otp_request_id', 'attempt_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_otp_verifications_request'), 'otp_verifications', ['otp_request_id'], unique=False)
    op.alter_column('otp_verifications', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.create_check_constraint(op.f('chk_otp_attempts'), 'otp_requests', 'attempts >= 0 AND attempts <= max_attempts')
    op.drop_constraint(None, 'otp_requests', type_='foreignkey')
    op.drop_index(op.f('ix_otp_requests_status'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_request_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_phone_number'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_expires_at'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_customer_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_created_at'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_application_id'), table_name='otp_requests')
    op.create_unique_constraint(op.f('otp_requests_request_id_key'), 'otp_requests', ['request_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_otp_status'), 'otp_requests', ['status'], unique=False)
    op.create_index(op.f('idx_otp_phone'), 'otp_requests', ['phone_number'], unique=False)
    op.create_index(op.f('idx_otp_expires'), 'otp_requests', ['expires_at'], unique=False)
    op.create_index(op.f('idx_otp_customer'), 'otp_requests', ['customer_id'], unique=False)
    op.create_index(op.f('idx_otp_created'), 'otp_requests', ['created_at'], unique=False)
    op.drop_column('otp_requests', 'application_id')
    op.drop_index(op.f('ix_meta_accounts_id'), table_name='meta_accounts')
    op.drop_index(op.f('ix_meta_accounts_customer_id'), table_name='meta_accounts')
    op.create_index(op.f('idx_meta_accounts_customer'), 'meta_accounts', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_provider_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_otp_request_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.create_index(op.f('idx_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('idx_messages_provider_id'), 'messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('idx_messages_otp_request'), 'messages', ['otp_request_id'], unique=False)
    op.create_index(op.f('idx_messages_customer'), 'messages', ['customer_id'], unique=False)
    op.create_index(op.f('idx_messages_created'), 'messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_message_events_message_id'), table_name='message_events')
    op.drop_index(op.f('ix_message_events_id'), table_name='message_events')
    op.drop_index(op.f('ix_message_events_event_type'), table_name='message_events')
    op.create_index(op.f('idx_message_events_type'), 'message_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_message_events_message'), 'message_events', ['message_id'], unique=False)
    op.alter_column('message_events', 'event_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'idempotency_keys', type_='foreignkey')
    op.drop_index(op.f('ix_idempotency_keys_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_customer_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_application_id'), table_name='idempotency_keys')
    op.create_index(op.f('idx_idempotency_customer'), 'idempotency_keys', ['customer_id'], unique=False)
    op.create_unique_constraint(op.f('idempotency_keys_customer_id_idempotency_key_endpoint_key'), 'idempotency_keys', ['customer_id', 'idempotency_key', 'endpoint'], postgresql_nulls_not_distinct=False)
    op.alter_column('idempotency_keys', 'response_body',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('idempotency_keys', 'application_id')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'email',
               existing_type=sa.String(length=255),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_customer_users_user'), 'customer_users', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_customer_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_user'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_customer'), 'audit_logs', ['customer_id'], unique=False)
    op.create_index(op.f('idx_audit_created'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'metadata_json')
    op.create_check_constraint(op.f('chk_api_keys_revoked'), 'api_keys', "status = 'revoked'::api_key_status AND revoked_at IS NOT NULL OR status <> 'revoked'::api_key_status")
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_status'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_customer_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_application_id'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_index(op.f('idx_api_keys_customer'), 'api_keys', ['customer_id'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'updated_at')
    op.drop_column('api_keys', 'environment')
    op.drop_column('api_keys', 'application_id')
    op.drop_index(op.f('ix_webhook_configs_id'), table_name='webhook_configs')
    op.drop_index(op.f('ix_webhook_configs_application_id'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_customer_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_meta_webhook_events_status'), table_name='meta_webhook_events')
    op.drop_index(op.f('ix_meta_webhook_events_meta_message_id'), table_name='meta_webhook_events')
    op.drop_index(op.f('ix_meta_webhook_events_id'), table_name='meta_webhook_events')
    op.drop_table('meta_webhook_events')
    # ### end Alembic commands ###
